site_name: CSC 3220 Winter 2019 Syllabus
theme: readthedocs

markdown_extensions:
  - footnotes
  - tables

pages:
  - Welcome: index.md
  - Instructor and Contact: contact.md
  - Course Overview: overview.md
  - Hybrid Class: hybrid.md
  - Textbook and Resources: textbook.md
  - Assignment and Grading: grading.md 
  - Attendence and Classroom Policies: classroom.md
  - CS/IS Learning Outcomes: outcomes.md
